### ISSUE TITLE
Some strings are not translated in _layouts

### ISSUE THREAD

**Issue by pyrog** [hotosm/learnosm#304]
**_layouts/default.html**
* Hosted on Github
* Official HOT OSM learning materials

**_layouts/doc.html**
* Link to this section

New strings should be added in **_config.yml** under ```translations:``` key:
```yml
translations:
  en:
    tagline: "Learn OpenStreetMap Step by Step"
    contribute: "Help improve our guides"
    trainingspan: "Are you a workshop organizer?"
    training: "Check out training material for this guide (in English)"
    feedbackspan: "Was this chapter helpful?"
    feedback: "Let us know and help us improve the guides!"
    getstarted: "Get started"
 ```
